### ISSUE TITLE
can not pass direction in departure()

### ISSUE THREAD

**Issue by dejavu1987** [derhuerst/vbb-hafas#19]
When I tried to pass station id of Hermanstrasse in direction option field, the following error is shown, also tried name of the station but did not work.
`hafas.departures('900000007102', {direction: '900000079221'})`

{ 
Error: HCI Service: location missing or invalid
    at hafasError (D:\dev\vbb-\node_modules\hafas-client\index.js:21:14)
    at got.post.then (D:\dev\vbb-\node_modules\hafas-client\index.js:46:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7) isHafasError:
 true }

**Comment by derhuerst** [comment]
Should have put a note into the docs about that. The problem is that **the HAFAS API doesn't allow putting station IDs as `direction` field**. You have to pass a station *name* in the correct form (which is ridiculous and basically renders the `direction` functionality useless). This `HCI Service` error comes from the HAFAS API.

There is a possible solution though. As [discussed before, I may implement a feature that allows you to specify the next station the vehicle will pass](https://forum.magicmirror.builders/post/26557). This can be really slow however, because it requires one additional request *per departure*.

I already implemented to similar use cases:

- [Using *static data* (which is brittle because of disruptions etc.), find the next departure by matching line names](https://github.com/derhuerst/vbb-anybar/blob/d84f196/next-departure-in-direction.js#L8-L32).
- [Find a matching *journey* (not a departure) that has a certain direction.](https://github.com/derhuerst/vbb-get-off-bot/blob/0c54c58/index.js#L35-L56)

cc @deg0nz

**Comment by derhuerst** [comment]
@deg0nz let's build this into your magic mirror app!

**Comment by deg0nz** [comment]
Awesome! Thanks @derhuerst!
I'm gonna implement this asap!
